config/routes.rb
Rails.application.routes.draw do

  get 'render/index'
  # root :to => 'pages#home' used to have this line, replaced with line 5
  root 'render#index'
  resources :users
  resources :shelters
  resources :animals

# This is NOT CRUD: don't use resources
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/favorites' => 'favorites#index'
  post '/favorites/:animal_id' => 'favorites#add_animal', :as => "animal_id"
  delete '/favorites/:animal_id' => 'favorites#remove_animal'
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :shelter, :optional => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_and_belongs_to_many :animals
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def new
    @animal = Animal.new
  end

  def create
    animal = Animal.new animal_params
    if params[:animal][:images].present?
      params[:animal][:images].each do |image|
        res = Cloudinary::Uploader.upload(image)
        animal.images << res["public_id"]
      end
    end
    animal.save
    redirect_to animals_path
  end

  def update
    animal = Animal.find params[:id]
    animal.update animal_params
    redirect_to animal
  end

  def edit
    @animal = Animal.find params[:id]
  end

  def show
    @animal = Animal.find params[:id]
  end

  def destroy
    animal = Animal.find params[:id]
    animal.destroy
    redirect_to animals_path
  end

  private
  def animal_params
    params.require(:animal).permit(:name, :species, :breed, :size, :gender, :age, :about, :hair_length, :adoption_cost, :shelter_id, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def add_animal
    animal = Animal.find params[:animal_id]
    @current_user.animals << animal
    redirect_to animal_path(animal)
  end

  def remove_animal
    animal = Animal.find params[:animal_id]
    @current_user.animals.delete(animal)
    redirect_to animal_path(animal)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @animals = Animal.all
  end
end

app/controllers/render_controller.rb
class RenderController < ApplicationController
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:error] = "invalid email or password"
      redirect_to login_path
    end
  end



  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  def index
    @shelters = Shelter.all
  end

  def new
    @shelter = Shelter.new
  end

  def create
    shelter = Shelter.new shelter_params
    shelter.save
    redirect_to shelters_path
  end

  def update
    shelter = Shelter.find params[:id]
    shelter.update shelter_params
    redirect_to shelter
  end

  def edit
    @shelter = Shelter.find params[:id]
  end

  def show
    @shelter = Shelter.find params[:id]
  end

  def destroy
    shelter = Shelter.find params[:id]
    shelter.destroy
    redirect_to shelters_path
  end

  private
  def shelter_params
    params.require(:shelter).permit(:name, :address, :phone, :email, :adoption_policy)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def show
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if params[:file].present?
      res = Cloudinary::Uploader.upload(params[:file])
      @user.image = res["public_id"]
    end
    if params[:user][:backyard_images].present?
      params[:user][:backyard_images].each do |image|
        res = Cloudinary::Uploader.upload(image)
        @user.backyard_images << res["public_id"]
      end
    end
    @user.update user_params
    redirect_to user_path(@user.id)
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :has_backyard, :backyard_image, :about, :has_pets, :pet_number, :pet_type, :animal_id)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/render_helper.rb
module RenderHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_form.html.erb
<div class="form-group">
    <%= form_for(@animal, :html => {:multipart => true}) do |a| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= a.label :name %>
        <%= a.text_field :name, :required => true, :autofocus => true, :class => 'form-control' %>

        <%= a.label :about %>
        <%= a.text_area :about, :class => 'form-control', :rows => 5 %>

        <%= a.label :species %>
        <%= a.text_field :species, :required => true, :class => 'form-control', :placeholder => "Cat" %>

        <%= a.label :breed %>
        <%= a.text_field :breed, :class => 'form-control' %>

        <%= a.label :size %>
        <%= a.text_field :size, :required => true, :class => 'form-control' %>
      </div>

      <div class="form-group col-md-6">
        <%= a.label :gender %>
        <%= a.text_field :gender, :required => true, :class => 'form-control' %>

        <%= a.label :age %>
        <%= a.text_field :age, :required => true, :class => 'form-control' %>

        <%= a.label :hair_length %>
        <%= a.text_field :hair_length, :class => 'form-control' %>

        <%= a.label :adoption_cost %>
        <%= a.number_field :adoption_cost, step: :any, :class => 'form-control' %>

        <%= a.label :upload_images %>
        <%= a.file_field :images, :multiple => true, :class => 'form-control-file my-3' %>

        <%= a.label :shelter_id %>
        <%= a.select :shelter_id, Shelter.pluck(:name, :id), :include_blank => true, :class => 'form-control' %>
      </div>
    </div>
  </div>
    <%= a.submit :class => 'btn btn-primary' %>
  <% end  %>

app/views/animals/edit.html.erb
<h1 class="my-3">Edit an animal listing </h1>

<%= render :partial => 'form' %>

<p class="my-3">Shelter not listed?
  <%= link_to "Add it here!", new_shelter_path %>
</p>

app/views/animals/index.html.erb
<div class="row justify-content-center my-3">
  <h1>Create happiness. Save lives.</h1>
</div>

<div class="row">

  <div class="col-md-6">
    <h2 class="animal-index">Cats</h2>
    <% @animals.each do |animal|  %>
      <% if animal.species.downcase == 'cat' %>
        <%= link_to cl_image_tag(animal.images.first, :class => 'thumb my-3'), animal%>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2 class="animal-index">Dogs</h2>
    <% @animals.each do |animal|  %>
      <% if animal.species.downcase == 'dog' %>
        <%= link_to cl_image_tag(animal.images.first, :class => 'thumb my-3'), animal%>
      <% end %>
    <% end %>
  </div>

</div>

app/views/animals/new.html.erb
<h1 class="my-3">Create a new animal listing</h1>

<%= render :partial => 'form' %>


<div class="row justify-content-center my-3">
  <p class="my-3">Shelter not listed?
    <%= link_to "Add it here!", new_shelter_path %>
  </p>
</div>

app/views/animals/show.html.erb
<div class="row justify-content-center my-3">
  <h1><%= @animal.name %></h1>
</div>

<div class="row">
  <div class="col-md-5">
    <%= cl_image_tag(@animal.images[0], :class => 'feature my-3 img-fluid') %>
    <% @animal.images.each do |image| %>
      <%= cl_image_tag(image, :class => 'thumb') %>
    <% end %>
  </div>

  <div class="col-md-5 offset-1">
    <h4 class="my-2">A beautiful
      <%= @animal.size %>
      <%= @animal.gender %>
      <%= @animal.breed %>
      looking for love!
    </h4>
    <h5>Age: <%= @animal.age %></h5>
    <h5>Hair length: <%= @animal.hair_length %></h5>
    <h5>Adoption cost: <%= number_to_currency(@animal.adoption_cost) %></h5>


    <p><%= @animal.about %></p>
    <% if @animal.shelter_id != nil %>
      <p>Adoption provided through - <%= link_to @animal.shelter.name, shelter_path(@animal.shelter.id) %></p>
    <% end %>

    <% if @current_user.present? %>
       <% if @current_user.animals.ids.include?(@animal.id) == true %>
          <%= button_to 'Unsave', animal_id_path(@animal), :method => :delete, :class => 'btn btn-secondary' %>
      <% else %>
        <%= button_to 'Save', animal_id_path(@animal), :class => 'btn btn-primary'%>
      <% end %>
    <% end %>
  </div>
</div>


<div class="row justify-content-center my-3">
  <p class="my-3">Animal listing incorrect?
    <%= link_to "Fix it!", edit_animal_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furever</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="container">
      <div class="header">
        <h1><%= link_to "Furever", root_path, :class => 'furever'%></h1>

        <nav>
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <% if @current_user.present? %>
                <%= link_to "My Home", user_path(@current_user.id), :class => "nav-link" %>
              <% else %>
                <%= link_to "Home", root_path, :class => "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "Animals", animals_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Shelters", shelters_path, :class => "nav-link" %>
            </li>
            <% if @current_user.present? %>
            <li class="nav-item">
              <%= link_to "Log out #{@current_user.email}", login_path, :method => 'delete', :class => "nav-link" %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_path, :class => "nav-link"%>
            </li>
              <li class="nav-item">
                <%= link_to "Login", login_path, :class => "nav-link"%>
            </li>
            <% end %>
          </ul>
        </nav>
      </div>
      <%= yield %>


    </div>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="row justify-content-center my-3">
    <h1>Welcome to <span class="fur">Furever</span></h1>
  </div>

  <p> Furever is a national animal welfare charity like no other. We help save thousands of lives every month by looking at the big picture, disrupting the status quo and finding innovative tech solutions to the biggest challenges facing rescue pets in Australia.</p>

  <p><%= link_to "Sign up", new_user_path %> and meet your furever friend today.</p>


<div class="row my-3">
  <div class="col-xs-12">
    <div class="carousel slide" data-ride="carousel">

      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="row">
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[8].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[1].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[2].images[0], :class => 'carousel-pic')  %>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="row">
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[3].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[4].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[5].images[0], :class => 'carousel-pic')  %>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="row">
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[6].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[7].images[0], :class => 'carousel-pic')  %>
            </div>
            <div class="col-xs-4">
              <%= cl_image_tag(@animals[0].images[0], :class => 'carousel-pic')  %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/render/index.html.erb
<h1>Render#index</h1>
<p>Find me in app/views/render/index.html.erb</p>

app/views/session/new.html.erb
<div class="row justify-content-center my-3">
  <h1>Welcome Back</h1>
</div>



<!-- THIS IS NOT CRUD -- we can't use form_for - form_tag requires the methods -->
<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<div class="form-group">
  <%= form_tag login_path do  %>
    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password  %>
    <%= password_field_tag :password  %>
</div>


    <%= submit_tag 'Sign In', :class => 'btn btn-primary' %>

<% end %>

app/views/shelters/_form.html.erb
<div class="form-group">
    <%= form_for(@shelter, :html => {:multipart => true}) do |s| %>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= s.label :name %>
        <%= s.text_field :name, :required => true, :autofocus => true, :class => 'form-control' %>

        <%= s.label :address %>
        <%= s.text_field :address, :class => 'form-control'%>

        <%= s.label :phone %>
        <%= s.text_field :phone, :class => 'form-control', :placeholder => '0411 305 208'%>

        <%= s.label :email %>
        <%= s.text_field :email, :class => 'form-control' %>

        <%= s.label :adoption_policy %>
        <%= s.text_area :adoption_policy, :rows => 3, :class => 'form-control' %>
      </div>
    </div>
  </div>
    <%= s.submit :class => 'btn btn-primary my-3' %>
  <% end  %>

app/views/shelters/edit.html.erb
<h1 class="my-3">Edit a shelter listing</h1>

<%= render :partial => 'form' %>

app/views/shelters/index.html.erb
<div class="row justify-content-center my-3">
  <h1>Shelters</h1>
</div>

<div class="col-md-6">
  <% @shelters.each do |shelter| %>
    <p><%= link_to shelter.name, shelter %></p>
  <% end %>
</div>



<div class="row justify-content-center my-3">
  <p>Don't see your shelter?
  <%= link_to "Add it!", new_shelter_path %></p>
</div>

app/views/shelters/new.html.erb
<h1 class="my-3">Create a new Shelter listing</h1>

<%= render :partial => 'form' %>

app/views/shelters/show.html.erb
<h1 class="my-3"><%= @shelter.name %></h1>



<p><%= @shelter.address %></p>
<p><%= number_to_phone(@shelter.phone, pattern: /(\d{4})(\d{3})(\d{3})$/)%></p>
<p><%= @shelter.email %></p>
<p><%= @shelter.adoption_policy %></p>

<h3>Our current residents:</h3>
<div class="row">
  <div class="col-md-12 ml-1">
    <% @shelter.animals.each do |animal| %>
      <p><%= link_to cl_image_tag(animal.images.first, :class => 'thumb float-left'), animal %></p>
    <% end %>
  </div>
</div>

<div class="row justify-content-center my-3">
  <p>See a mistake and want to fix it?
  <%= link_to "Go ahead!", edit_shelter_path %>
  Or, add a
  <%= link_to "new animal", new_animal_path %>
  to this shelter!</p>
</div>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form_for(@user, :html => {:multipart => true}) do |u| %>
    <%= u.label :name %>
    <%= u.text_field :name, :required => true, :autofocus => true, :class => 'form-control' %>

    <%= u.label :about %>
    <%= u.text_area :about, :class => 'form-control' %>

    <fieldset class="form-group">
      <div class="row mt-3">
        <legend class="col-form-label col-sm-2 pt-0">Do you have a fenced backyard?</legend>
        <div class="col-sm-10">
          <div class="form-check form-check-inline my-3">
            <%= u.label :has_backyard, "Yes", :value => "true", :class => "form-check-label" %>
            <%= u.radio_button :has_backyard, true, :class => "form-check-input" %>
            <%= u.label :has_backyard, "No", :value => "false", :class => "form-check-label" %>
            <%= u.radio_button :has_backyard, false, :class => "form-check-input" %>
          </div>
        </div>
      </div>
    </fieldset>

    <%= u.label :upload_backyard_images, "Upload backyard images: (up to 4)" %>
    <%= u.file_field :backyard_images, :multiple => true, :class => 'form-control-file' %>


    <fieldset class="form-group">
      <div class="row mt-3">
        <legend class="col-form-label col-sm-2 pt-0">Do you have other pets?</legend>
        <div class="col-sm-10">
          <div class="form-check form-check-inline my-3">
            <%= u.label :has_pets, "Yes", :value => "true", :class => "form-check-label" %>
            <%= u.radio_button :has_pets, true, :class => "form-check-input" %>
            <%= u.label :has_pets, "No", :value => "false", :class => "form-check-label" %>
            <%= u.radio_button :has_pets, false, :class => "form-check-input" %>
          </div>
        </div>
      </div>
    </fieldset>


    <%= u.label :pet_number, "How many?" %>
    <%= u.number_field(:pet_number, step: 1.0, :min => 0)%>


    <div class="form-group mt-3">
      <%= u.label :pet_type, "Pet type:" %>
      <%= u.text_field :pet_type, :class => 'form-control-file', :placeholder => "2 dogs, and one cat" %>
    </div>

    <%= u.label :image, "Upload profile picture:" %>
    <%= u.cl_image_upload :image, :class => 'form-control-file' %>

  </div>
  <%= u.submit :class => 'btn btn-primary' %>
<% end  %>

app/views/users/edit.html.erb
<h2>Update your profile
  <% @user = User.find session[:user_id] %>
  <% if @user.name != nil %>
    <%= @user.name %>
  <% end %>
</h2>



<%= render :partial => 'form' %>

app/views/users/index.html.erb
<h1>All Users</h1>
<h3>HIDE THIS TO ALL BUT ADMINS</h3>

<% @users.each do |user|  %>

<p><%= user.email %> ---- <%= user.name %> --- <%= user.about %></p>


<% end  %>

app/views/users/new.html.erb
<div class="row justify-content-center my-3">
  <h1>Welcome</h1>
</div>
<p>Sign up for one-click submissions to the most comprehensive list of rescue animals in Australia.</p>
<p>Already a member? <a href="/login">Login!</a></p>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end  %>

<%=  form_for @user do |f| %>


  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control'%>

    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div>

  <%= f.submit "Sign up", :class => 'btn btn-primary'%>

<% end %>

app/views/users/show.html.erb
<% if @current_user.present? %>

  <div class="row justify-content-center my-3">
    <% if @current_user.name != nil %>
      <h1>Welcome, <%= @current_user.name %></h1>
    <% else %>
      <h2>Welcome</h2>
    <% end %>
  </div>

  <div class="row">
    <div class="col-md-5 offset-md-1">
      <% if @current_user.image != nil %>
        <%= cl_image_tag @current_user.image, :class => 'feature img-fluid'%>
      <% end %>
      <% if @current_user.has_backyard != nil %>
        <h4 class="my-3 title-left">Enclosed backyard?</h4>
          <% if @current_user.has_backyard == false && @current_user.backyard_images.size < 1%>
            <p>Unfortunately not, only cats or low energy dogs for me.</p>
          <% else %>
            <p>Sure do! I can care for any kind of pet!</p>
          <% end %>
      <% end %>
      <% if @current_user.backyard_images.size > 0 %>
        <% @current_user.backyard_images.each do |image| %>
          <%= cl_image_tag image, :class => 'backyard'%>
        <% end %>
      <% end %>
      <% if @current_user.has_pets != nil %>
        <h4 class="my-3 title-left">Other pets?</h4>
          <% if @current_user.has_pets == true || @current_user.pet_number != nil %>
            <p>Absolutely! Can't live without them!</p>
          <% else %>
            <p>Not yet, I'm waiting to find one that's just right!</p>
          <% end %>
      <% end %>
      <% if @current_user.pet_number != nil && @current_user.pet_number != 0 %>
        <h4 class="my-3 title-left">How many pets?</h4>
        <p><%= @current_user.pet_number%>
        <% if @current_user.pet_type != nil && @current_user.pet_number > 0 %>
          <%= @current_user.pet_type %>.
          </p>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-5 offset-md-1">
      <% if @current_user.about != nil %>
        <h4 class="title-right my-3">About me:</h4> <p><%= @current_user.about %></p>
      <% end %>
      <% if @current_user.animals.size > 0 %>
        <h4 class="title-right my-3">Furever friends I love:</h4>
          <% @current_user.animals.each do |animal| %>
            <%= link_to cl_image_tag(animal.images.first, :class => 'thumb float-left my-1'), animal %>
          <% end %>
      <% end %>
    </div>
  </div>




      <div class="row justify-content-center my-3">
          <p>Do you want to update the rest of your profile now?</p><br>
      </div>

      <div class="row justify-content-center my-3">
        <div class="col-md-2">
          <%= button_to 'Yes!', edit_user_path(@current_user), :method => :get, :class => 'btn btn-primary'%>
        </div>
        <div class="col-md-2">
          <%= button_to 'No, show me the Animals!', animals_path, :method => :get, :class => 'btn btn-secondary'%>
        </div>
      </div>


<%end %>